# Numpy 
## Numpy - element wise functions 元素操作函数
对每个元素操作的函数
- abs, fabs, sqrt, squre, exp, log, log10, log2, log1p
- sign-取符号, ceil-向上取整, floor-向下取整, rint-四舍五入, modf-小数整数分离, isnan, isfinit, isinf
- cos,cosh,sin,sinh,tan,tanh,arccos,arccoh,arcsin,arcsinh,arctan,arctanh
- add,sustract,multiply,divide,floor_divide,power
- maximum,fmax,minimum,fmin,mod,copysign
- greater,greater_equal,less,less_equal,equal,not_equal,logical_and,logical_or,logical_xor,logical_not

In [2]:
## 一元函数 unary
import numpy as np

arr = np.arange(10)
print(arr)
# 开平方
print(np.sqrt(arr))
# 指数函数
print(np.exp(arr))

[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [3]:
## binary 二元函数
# randn = random + normal 随机正态分布
x = np.random.randn(8)
y = np.random.randn(8)
print(x)
print(y)
# 求最大值
print(np.maximum(x,y))

[-0.35233803 -1.56877642  1.69968217  1.20562621  0.40802483 -0.91186135
 -1.31666442 -0.12981717]
[-0.5529226  -1.09425143 -1.10740299  1.86792047  0.72381972  1.5985426
  0.54179412 -0.28744764]
[-0.35233803 -1.09425143  1.69968217  1.86792047  0.72381972  1.5985426
  0.54179412 -0.12981717]


## inplace "原位"操作
- 所有的操作都是“就地”操作,不允许进行移动
- 尤其适合内存不足的情况

In [5]:
## inplace "原位"操作
# 所有的操作都是“就地”操作,不允许进行移动
arr = np.array([-0.35233803, -1.56877642,  1.69968217,  1.20562621,  0.40802483, -0.91186135, -1.31666442, -0.12981717])
print(np.sqrt(arr))
print(arr)
# inplace “原位”操作
print(np.sqrt(arr,arr))
# 改变了原数组的值
print(arr)
# nan - not a number

[       nan        nan 1.30371859 1.09801011 0.63876821        nan
        nan        nan]
[-0.35233803 -1.56877642  1.69968217  1.20562621  0.40802483 -0.91186135
 -1.31666442 -0.12981717]
[       nan        nan 1.30371859 1.09801011 0.63876821        nan
        nan        nan]
[       nan        nan 1.30371859 1.09801011 0.63876821        nan
        nan        nan]


C:\Anaconda3\envs\python3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.
C:\Anaconda3\envs\python3\lib\site-packages\ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in sqrt
  import sys


## Numpy - array function 数组操作函数
- sum-求和,mean-均值,
- std-标准差,var-方差
- min-最小值,max-最大值,argmin-最小值元素,argmax-最大值元素
- cumsum-累加求和,cumprod-累加乘积

In [12]:
arr = np.random.randn(5,4)
print(arr)
# 求均值
print(arr.mean())
print(np.mean(arr))
# 求和
print(arr.sum())
print(np.sum(arr))
# 条件求和
print((arr > 0).sum())
# 按某个坐标轴求均值
print(arr.mean(axis=1))
# 按某个坐标轴求和
print(arr.sum(axis=0))
# 求累加和
print(arr.cumsum())
print(arr.cumsum(axis=0))

[[-0.52483718  0.07750143 -0.15198024 -0.26957984]
 [-0.74371785 -0.45853156 -1.27812063  0.73037314]
 [-1.00775661  0.52795874  0.1662487   1.49585349]
 [-0.07365622 -0.94438777 -0.22697649  1.14764035]
 [ 0.28538996  0.89246024 -0.17646771 -1.75689404]]
-0.11447400477916383
-0.11447400477916383
-2.2894800955832766
-2.2894800955832766
8
[-0.21722396 -0.43749923  0.29557608 -0.02434503 -0.18887789]
[-2.06457791  0.09500108 -1.66729636  1.3473931 ]
[-0.52483718 -0.44733575 -0.59931598 -0.86889583 -1.61261368 -2.07114525
 -3.34926588 -2.61889274 -3.62664935 -3.09869061 -2.9324419  -1.43658841
 -1.51024464 -2.4546324  -2.68160889 -1.53396855 -1.24857859 -0.35611835
 -0.53258606 -2.2894801 ]
[[-0.52483718  0.07750143 -0.15198024 -0.26957984]
 [-1.26855504 -0.38103013 -1.43010087  0.4607933 ]
 [-2.27631165  0.14692861 -1.26385217  1.95664679]
 [-2.34996787 -0.79745916 -1.49082865  3.10428713]
 [-2.06457791  0.09500108 -1.66729636  1.3473931 ]]


In [14]:
# 布尔数组的函数
bools = np.array([False,False,True,False])
# 任何一个元素为真，返回真
print(bools.any())
# 所有元素为真，返回真
print(bools.all())

True
False


In [18]:
# 排序
arr = np.random.randn(6)
print(arr)
arr.sort()
print(arr)
# 按某个坐标轴排序
arr = np.random.randn(5,3)
print(arr)
arr.sort(0)
print('-'*20)
print(arr)

[ 0.33552324  2.37094047 -0.11068084  0.5453685  -0.79519909  1.00856127]
[-0.79519909 -0.11068084  0.33552324  0.5453685   1.00856127  2.37094047]
[[ 1.01277269  0.34842224 -1.54738896]
 [-1.0206474  -1.75021605 -0.70490509]
 [-2.51853057  0.53660079  0.63093401]
 [-0.58978646  0.23575388 -1.57938108]
 [-0.26224745 -1.17084857 -0.64633248]]
--------------------
[[-2.51853057 -1.75021605 -1.57938108]
 [-1.0206474  -1.17084857 -1.54738896]
 [-0.58978646  0.23575388 -0.70490509]
 [-0.26224745  0.34842224 -0.64633248]
 [ 1.01277269  0.53660079  0.63093401]]


## Numpy - set function 集合操作函数
- unique(x)-列表去重排序
- intersect1d(x,y)-排序交集
- union1d(x,y)-排序并集
- in1d(x,y)-判断x的每个元素是否在y中
- setdiff1d(x,y)-(x-y)的差集
- setxor1d(x,y)-补集

In [21]:
# 列表去重
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
print(np.unique(names))
ints = np.array([3,3,3,2,2,1,1,4,4])
print(np.unique(ints))
# 判断是否在集合中
values = np.array([6,0,0,3,2,5,6])
print(np.in1d(values,[2,3,6]))
print(np.in1d([2,3,6],values))

['Bob' 'Joe' 'Will']
[1 2 3 4]
[ True False False  True  True False  True]
[ True  True  True]


## Numpy - where 条件逻辑
```python
    numpy.where(cond,true_res,false_res)
```

In [22]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
print(np.where(cond,xarr,yarr))

[1.1 2.2 1.3 1.4 2.5]


In [23]:
arr = np.random.randn(4,4)
print(arr)
print('-'*20)
print(np.where(arr > 0, 2, arr))

[[-0.62692815  1.62615284 -0.97428028  1.00908838]
 [ 1.92994521  1.28319427 -1.33475276 -0.12073904]
 [ 0.35608264  0.26990468 -0.00899892  1.09197816]
 [ 0.62263855  1.70197785 -2.4501422   1.83826516]]
--------------------
[[-0.62692815  2.         -0.97428028  2.        ]
 [ 2.          2.         -1.33475276 -0.12073904]
 [ 2.          2.         -0.00899892  2.        ]
 [ 2.          2.         -2.4501422   2.        ]]


## Numpy - broadcasting 数组扩维
[numpy 中 broadcasting 的理解](https://www.cnblogs.com/pied/p/8288856.html)

In [29]:
xarr = np.arange(12).reshape(3,4)
# ValueError: operands could not be broadcast together with shapes (3,4) (1,3) 
# yarr = np.ones(3).reshape(3,1)
# okay
yarr = np.ones(3).reshape(1,3) 
# ValueError: operands could not be broadcast together with shapes (3,4) (3,) 
# yarr = np.ones(3)
# okay
yarr = np.ones(4)
print(xarr)
print('-'*20)
print(yarr)
print('-'*20)
print(xarr+yarr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------
[1. 1. 1. 1.]
--------------------
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [36]:
xarr = np.arange(24).reshape(2,3,4)
# ValueError: operands could not be broadcast together with shapes (2,3,4) (2,3) 
# yarr = np.ones(6).reshape(2,3)
# okay
yarr = np.ones(12).reshape(3,4)
# okay
yarr = np.ones(12).reshape(1,3,4)
# okay
yarr = np.ones(8).reshape(2,1,4)
# okay
yarr = np.ones(6).reshape(2,3,1)
print(xarr)
print('-'*20)
print(yarr)
print('-'*20)
print(xarr+yarr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
--------------------
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]
--------------------
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]]


## Numpy - linear algebra 线性代数
- diag-对角阵
- dot-点积
- trace-迹（方阵，对角线元素之和）
- det-行列式
- eig-特征值和特征向量
- inv-逆,pinv-伪逆
- qr-QR分解
- svd-奇异值分解
- solve-求解线性方程AX=b
- lstsq-最小二乘法解线性方程AX=b

In [37]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1.,7.],[8.,9.]])
# 内积
print(x)
print('-'*20)
print(y)
print('-'*20)
print(x.dot(y))

[[1. 2. 3.]
 [4. 5. 6.]]
--------------------
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
--------------------
[[ 28.  64.]
 [ 67. 181.]]


In [39]:
# 转置，逆矩阵，QR分解
from numpy.linalg import inv,qr
X = np.random.randn(5,5)
# 转置
mat = X.T.dot(X)
print(X)
print('-'*20)
print(X.T)
print('-'*20)
print(mat)
print('-'*20)
# 逆矩阵
res = mat.dot(inv(mat))
print(inv(mat))
print('-'*20)
print(res)
print('-'*20)
# QR分解
q,r = qr(mat)
print(q)
print('-'*20)
print(r)

[[-1.4578384  -1.6771046   0.16742732 -0.10114284 -1.6861579 ]
 [ 2.02510864  0.00749223  1.69924333  0.13404784  0.49528036]
 [-0.93942279 -1.74176497 -1.99184078 -0.62912354 -1.84442582]
 [-0.57544483  0.51495792 -0.66183933  0.50876864  1.55778877]
 [-0.07033738 -0.69228948  1.15928573  0.52418508  0.61428269]]
--------------------
[[-1.4578384   2.02510864 -0.93942279 -0.57544483 -0.07033738]
 [-1.6771046   0.00749223 -1.74176497  0.51495792 -0.69228948]
 [ 0.16742732  1.69924333 -1.99184078 -0.66183933  1.15928573]
 [-0.10114284  0.13404784 -0.62912354  0.50876864  0.52418508]
 [-1.6861579   0.49528036 -1.84442582  1.55778877  0.61428269]]
--------------------
[[7.44495707 3.84873773 5.36756191 0.68028626 4.2542094 ]
 [3.84873773 6.59092754 2.05787578 1.1655234  6.42106442]
 [5.36756191 2.05787578 8.66486422 1.73491694 3.91421881]
 [0.68028626 1.1655234  1.73491694 0.95761065 2.51185765]
 [4.2542094  6.42106442 3.91421881 2.51185765 9.29438676]]
--------------------
[[  51.0309452